### ISSUE TITLE
No matter how many times i try the code exits after running command "model = load_model(location)" in drive.py

### ISSUE THREAD

**Issue by hemanth2410** [hadipash/AI_GTA5#3]
![screenshot 150](https://user-images.githubusercontent.com/24288422/53193358-c8697880-3636-11e9-8747-b03ea429e464.png)

**Comment by hemanth2410** [comment]
I am guessing the model file is corrupted, after cloning repo the model file is only about 3698 kb

**Comment by hadipash** [comment]
Hi! Thanks for your inquiry.

The model file is fine, just the procedure of making the program work is a bit complicated. Until now didn't have much time to write a good guideline.

The most important you need to know before you start is that the program works only with Korean version of GTA V due to fonts. Unfortunately, in English version fonts are not monospaced and it made difficult to read important information from the screen.

Then, you also need to consider next:
1. The code was tested in PyCharm and might not work with python idle (you can download PyCharm for free using student subscription https://www.jetbrains.com/student/)
2. The code was tested using python 3.6. You might want to switch to that version.
3. The code 100% does not work with anaconda (in fact, tensorflow officially has no support in anaconda).

Let me know if you still have problems.

**Comment by hemanth2410** [comment]
Thanks for the help sir

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hemanth2410** [comment]
so far i can see only lanes, but i dont see any boxes surrounding people, traffic lights etc

**Comment by hadipash** [comment]
Now, to run the model need to adjust some parameters. Because tuning depends on several conditions including your hardware (GTA V outlook differs from version to version and hardware), it is better to do it through pm. Could you message me through linkedin?

**Comment by Duskfall** [comment]
My error has to do with darkflow not loading properly.
Using Python 3.6,
Pycharm 2018.3.5
Windows 10
Installed darkflow globally with pip install . after cloning the project
Getting error
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/backup/MasterUOM/Thesis/AI_GTA5/driving/drive.py", line 21, in <module>
    from object_detection.object_detect import yolo_detection
  File "C:\backup\MasterUOM\Thesis\AI_GTA5\object_detection\object_detect.py", line 3, in <module>
    from darkflow.net.build import TFNet
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\darkflow\net\build.py", line 5, in <module>
    from .ops import op_create, identity
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\darkflow\net\ops\__init__.py", line 1, in <module>
    from .simple import *
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\darkflow\net\ops\simple.py", line 1, in <module>
    import tensorflow.contrib.slim as slim
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\__init__.py", line 41, in <module>
    from tensorflow.contrib import distribute
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distribute\__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import initialize_tpu_system
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\distribute\python\tpu_strategy.py", line 27, in <module>
    from tensorflow.contrib.tpu.python.ops import tpu_ops
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\__init__.py", line 73, in <module>
    from tensorflow.contrib.tpu.python.tpu.keras_support import tpu_model as keras_to_tpu_model
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\python\tpu\keras_support.py", line 61, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\tpu\python\tpu\tpu.py", line 25, in <module>
    from tensorflow.contrib.compiler import xla
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\contrib\compiler\xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\estimator\__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py", line 22, in <module>
    from tensorflow_estimator.python.estimator.canned.baseline import BaselineClassifier
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\canned\baseline.py", line 64, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 66, in <module>
    from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\model_fn.py", line 36, in <module>
    from tensorflow_estimator.python.estimator.export import export_lib
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\export\export_lib.py", line 39, in <module>
    from tensorflow_estimator.python.estimator.export.export import build_parsing_serving_input_receiver_fn
  File "C:\Users\duskfall\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\export\export.py", line 38, in <module>
    from tensorflow.python.saved_model.model_utils.export_utils import SINGLE_FEATURE_DEFAULT_NAME
ImportError: cannot import name 'SINGLE_FEATURE_DEFAULT_NAME'
```

**Comment by Duskfall** [comment]
Hello, thanks for the great repo!
Using Python 3.6,
Pycharm 2018.3.5
Windows 10
tensorflow_gpu-1.13.1
Installed darkflow globally with pip install . after cloning the project
How can I use the auto drive mode? I get to Arrived at destination when pressing T. Also I only see the boxes instead of the lanes

**Comment by hemanth2410** [comment]
i can help can you please send me screen shot of output. mail me saihemanth.s@outlook.com


________________________________

**Comment by hemanth2410** [comment]
try setting marker on map and then press T on keyboard.

and please make sure that you are in first person move (Hood camera).

and paint both primary and secondary colors to matte black.

enable speed info (KMPH only) from sample trainer.

this worked for me 

and thanks hadipash for guiding me.

**Comment by Duskfall** [comment]
@hemanth2410 can you plz clarify those 2? :P

> and paint both primary and secondary colors to matte black.
> 
> enable speed info (KMPH only) from sample trainer.

**Comment by hemanth2410** [comment]
step 1-> install openIV and select GTA 5 location in it.
step 2 -> Enable Edit mode
step 3 -> Go to x64a.rpf
step 4 -> Go to textures folder
step 5 -> (Right click) on graphics.ytd and select edit
step 6 -> Search for radarmasksm
step 6 -> replace it with https://1drv.ms/u/s!Au9TCMuJ7_EbhvVjoQVV5xXwzgIjnQ
step 7 -> remove any trainers that you have previously installed.
step 8 -> install this trainer to gta 5 https://www.gta5-mods.com/scripts/simple-trainer-for-gtav
step 9 -> press F4 to open trainer menu
step 10 -> Use your number pad keys to navigate in menu.
step 11 -> go to vehicle spawning -> sports -> select Lampadati Furore GT.
step 12 -> go into vehicle options in trainer menu -> vehicle color oprions.
step 13 -> select matte black for both primary and secondary color options.
step 14 -> go to general options and select display speed info KMPH
step 15 -> make sure that you are running game in 800 x 600 windowed mode.
step 16 -> identify speed. https://1drv.ms/u/s!Au9TCMuJ7_EbhvVktW3jjxmI82rxFQ
step 17 -> vis = image[568:576, 681:700, :]
step 18 -> 
![screenshot 2](https://user-images.githubusercontent.com/24288422/53775988-897ed100-3f1a-11e9-9c12-23a6dad9dc51.png)

you should get output something like this.

step 19 -> make sure that you set values like 576-568 = 8 px and 700-681 = 19 px. 
                  the values of width and height should be 8 and 19.
step 20 -> if you got this far then you are probably ready to perform self driving 
step 21 -> in repo folder go to object_detection -> object_Detect.py, under # set yolo options change gpu value to 0.4
step 22 -> save the py file.
step 23 -> now set waypoint on map.
step 24 -> run drive.py code.

optional steps if Gpu is <= 4GB

step 25 -> if you have ssd try running code on ssd.
step 26 -> tune gpu value in object_detect.py

**Comment by hemanth2410** [comment]
@hadipash  any plans in upgrading this code, sir?

**Comment by hadipash** [comment]
@hemanth2410 As much as I would love to improve this project, I simply don't have time for this. So, no plans on any upgrades.
